name: "Run GenTree Unit Tests"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the runner image
      run: docker build -f run-unit-tests.Dockerfile --tag=owl/gentree_test:0.1 .
    - name: Run the tests
      run: docker run --rm owl/gentree_test:0.1
